config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers:
    {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations'
    }

  devise_scope :user do
    get 'email_required', to: 'registrations#email_required'
    post 'create_with_email', to: 'registrations#create_with_email'
    resources :users
  end

  root 'questions#index'
  get 'search', to: 'sphinx#search'

  concern :voteable do
    member do
      post 'vote_plus'
      post 'vote_minus'
      post 're_vote'
    end
  end

  concern :commentable do
    resources :comments, only: [:create, :show]
  end

  concern :tagged do
    get 'tagged/:tag', on: :collection, action: 'tagged_list', as: 'tagged'
  end

  resources :questions, concerns: [:voteable, :commentable, :tagged] do
    post 'subscribe', on: :member
    post 'unsubscribe', on: :member

    resources :answers, concerns: [:voteable, :commentable] do
      post 'best_answer', on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create]
      end
    end
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  include Attachable
  include Voteable
  include Commentable
  include Taggable

  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :followers, through: :subscriptions, source: :user
  belongs_to :user

  validates :title, :body, :user_id, presence: true

  # rubocop:disable Metrics/LineLength
  scope :created_yesterday, -> { where(created_at: Date.yesterday.beginning_of_day..Date.yesterday.end_of_day) }

  scope :with_includes, lambda {
    eager_load(:attachments, comments: :user)
      .order('comments.created_at')
      .includes(:answers).eager_load(:attachments, comments: :user)
  }

  scope :any_tags, -> (tags) { where('tags && ARRAY[?]', tags) }
  scope :all_tags, -> (tags) { where('tags @> ARRAY[?]', tags) }

  default_scope { order(created_at: :desc) }

  after_create :subscribe_author

  def subscribe(user)
    followers << user unless followers.include? user
  end

  def unsubscribe(user)
    subscriptions.find_by(user_id: user).destroy if followers.include? user
  end

  private

  def subscribe_author
    followers << user
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource Question

  def index
    respond_with Question.all, each_serializer: QuestionsListSerializer
  end

  def show
    respond_with Question.find(params[:id])
  end

  def create
    respond_with current_resource_owner.questions.create(question_params)
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include VoteableController
  include TaggedController

  before_action :authenticate_user!, only: [:new, :create, :destroy, :update]
  before_action :load_question, only: [:destroy, :update, :subscribe, :unsubscribe]
  before_action :load_question_with_includes, only: :show
  before_action :build_answer, only: :show
  after_action :publish_new_question, only: :create

  respond_to :html
  respond_to :js, only: [:update, :subscribe, :unsubscribe]

  authorize_resource

  def index
    respond_with(@questions = Question.eager_load(:user).all)
  end

  def show
    gon.current_user_id = current_user.id if current_user
    respond_with @question
  end

  def new
    respond_with @question = Question.new
  end

  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def destroy
    @question.destroy if @question.user_id == current_user.id
    respond_with @question
  end

  def update
    @question.update(question_params)
    respond_with @question
  end

  def subscribe
    respond_with @question.subscribe(current_user)
  end

  def unsubscribe
    respond_with @question.unsubscribe(current_user)
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file, :id, :_destroy])
  end

  def load_question
    @question = Question.find(params[:id])
  end

  def publish_new_question
    return unless @question.valid?
    PrivatePub.publish_to '/questions', question: render_to_string(
      partial: 'question',
      locals: { question: @question })
  end

  def load_question_with_includes
    @question = Question.with_includes.find(params[:id])
  end

  def build_answer
    @answer = @question.answers.build
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def hashtags_to_links(text)
    text
      .gsub(Question::HASHTAG_REGEXP_PATTERN) { hashtag_link(Regexp.last_match(1)) }
      .html_safe
  end

  def hashtag_link(hashtag)
    link_to("##{hashtag}", tagged_questions_path(hashtag.downcase))
  end
end

app/views/questions/_controls.html.slim
- if current_user
  .subscribe-controls
    - if @question.followers.include? current_user
        = link_to 'Unsubscribe', unsubscribe_question_path(@question), method: :post, remote: true
    - else
      = link_to 'Subscribe', subscribe_question_path(@question), method: :post, remote: true

- if can?(:manage, @question)
  - cache [@question, :controls]
    .question-managing-controls
      ul.clear
        li
          = link_to 'Edit', '', class: 'edit-question-link'
        li
          = link_to 'Delete question', @question, method: :delete

app/views/questions/_form.html.slim
- cache [@question, :edit_form]
  = form_for @question, remote: remote do |f|
    p= f.label :title
    p= f.text_field :title
    p= f.label :body
    p= f.text_area :body

    p Attachments:
    div
      = f.fields_for :attachments do |a|
        = render 'shared/attachment_fields', f: a
      .links
        = link_to_add_association 'add file', f, :attachments, partial: 'shared/attachment_fields'

    p= f.submit submit_text

app/views/questions/_question.html.slim
div class="question question_#{question.id}" id="#{dom_id question}"

  .votes
    .count
      = question.votes_sum
    div
      | votes
  .answers
    .count
      = question.answers_count
    div
      | answers

  .summary
    h4
      = link_to question.title, question_path(question)

    - if question.tags.any?
      = render 'shared/tags_list', question: question

  = render 'shared/author_info', object: question

app/views/questions/_question_block.html.slim
.question-header
  h3= @question.title

  table.post
    tbody
      tr
        td.vote-cell
          .votes-container
            = render partial: 'shared/votes', locals: { object: @question }
        td.post-cell
          .post-content
            .post-body
              - cache [@question, :body]
                = hashtags_to_links @question.body

              - if @question.attachments.any?
                - cache_unless [@question, :attachments]
                  = render 'shared/attached_files', files: @question.attachments

            - if @question.tags.any?
              = render 'shared/tags_list', question: @question

            .post-footer
              .post-controls
                = render 'questions/controls'

              - cache [@question, :author_info]
                = render 'shared/author_info', object: @question

          #edit-question-form-container
            div#validation-errors
            = render partial: 'form', locals: { submit_text: 'Save', remote: true }

app/views/questions/_validation_errors.html.slim
- if @question.errors.any?
  ul
    - @question.errors.full_messages.each do |msg|
      li= msg

app/views/questions/index.html.slim
- cache collection_cache_key_for :question
  .section
    .container
      .row
        .col-md-12
          h3 Questions list
      .row
        .col-md-12
          - if @questions.any?
            .questions-list-container
              - @questions.each do |question|
                - cache [question, :questions_list_item]
                  = render question, question: question
          - else
            div
              | Questions is empty

= subscribe_to '/questions'

app/views/questions/new.html.slim
- if @question.errors.any?
  ul
    - @question.errors.full_messages.each do |msg|
      li= msg

= render partial: 'form', locals: { submit_text: 'Create', remote: false }

app/views/questions/show.html.slim
.question id="#{dom_id @question}"
  = render 'question_block'

  table
    tr
      td.vote-cell
      td.post-cell
        = render 'comments/list', commentable: @question



.answers data={question_id: "#{@question.id}"}
  = render 'answers/answers_list'

  - if can?(:create, Answer)
    = render 'answers/new_answer_form', question: @question

= subscribe_to "/questions/#{@question.id}/answers"

app/views/questions/subscribe.js.erb
$('.flash-msgs').append('<div class="alert alert-success" role="alert"><%= j flash[:notice] %></div>');

$('.question .subscribe-controls').html('<%= j link_to 'Unsubscribe', unsubscribe_question_path(@question), method: :post, remote: true %>');

app/views/questions/tagged_list.html.slim
.section
  .container
    .row
      .col-md-12
        h3 Questions list
    .row
      .col-md-12
        - if @questions.any?
          .questions-list-container
            - @questions.each do |question|
              - cache [question, :questions_list_item]
                = render question, question: question
        - else
          div
            | Questions is empty

app/views/questions/unsubscribe.js.erb
$('.flash-msgs').append('<div class="alert alert-success" role="alert"><%= j flash[:notice] %></div>');

$('.question .subscribe-controls').html('<%= j link_to 'Subscribe', subscribe_question_path(@question), method: :post, remote: true %>');

app/views/questions/update.js.erb
<% if @question.valid? %>
  <% if remotipart_submitted? %>
    $('div.question').html("<%= j "#{render('question_block')}" %>");
  <% else %>
    $('div.question').html('<%= j render "question_block" %>');
  <% end %>
  $('div#edit-question-form-container').hide();
<% else %>
  $('div#edit-question-form-container #validation-errors').html('<%= j render "validation_errors" %>');
<% end %>