config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers:
    {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations'
    }

  devise_scope :user do
    get 'email_required', to: 'registrations#email_required'
    post 'create_with_email', to: 'registrations#create_with_email'
    resources :users
  end

  root 'questions#index'
  get 'search', to: 'sphinx#search'

  concern :voteable do
    member do
      post 'vote_plus'
      post 'vote_minus'
      post 're_vote'
    end
  end

  concern :commentable do
    resources :comments, only: [:create, :show]
  end

  concern :tagged do
    get 'tagged/:tag', on: :collection, action: 'tagged_list', as: 'tagged'
  end

  resources :questions, concerns: [:voteable, :commentable, :tagged] do
    post 'subscribe', on: :member
    post 'unsubscribe', on: :member

    resources :answers, concerns: [:voteable, :commentable] do
      post 'best_answer', on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create]
      end
    end
  end

end

app/views/shared/_attached_files.html.slim
p Attachments
ul
  - files.each do |a|
    - unless a.new_record?
      li
        = link_to a.file.identifier, a.file.url

app/views/shared/_attachment_fields.html.slim
.field
  - if f.object.new_record?
    = f.label :file
    = f.file_field :file
  - else
    = f.text_field :file, value: f.object.file.identifier
= link_to_remove_association 'remove file', f

app/views/shared/_author_info.html.slim
.user-info
  .created-at
    span.timeago title="#{object.created_at.getutc.iso8601}"
      = object.created_at.to_s

  .user-avatar-32
    - if object.user.avatar.thumb.url
      = image_tag object.user.avatar.thumb
    - else
      p.no-avatar-thumb No avatar

  .user-details
    = link_to object.user.nickname, user_path(object.user)

app/views/shared/_tags_list.html.slim
div.tags-list
  - question.tags.each do |tag|
    = link_to tag, tagged_questions_path(tag)

app/views/shared/_votes.html.slim
div.votes-links
  - if can?(:vote, object)
    - if object.user_is_voted?(current_user)
      .votes-sum
        p
          = object.votes_sum
      p
        - if object.kind_of? Question
          =  link_to 'Re-vote?', re_vote_question_path(object), remote: true, method: :post, class: 're-vote'

        - if object.kind_of? Answer
          =  link_to 'Re-vote?', re_vote_question_answer_path(object.question, object), remote: true, method: :post, class: 're-vote'

    - else

      .votes-link.vote-plus
        - if object.kind_of? Question
          = link_to '+', vote_plus_question_path(object), remote: true, method: :post, class: 'vote-plus'
        - if object.kind_of? Answer
          = link_to('+', vote_plus_question_answer_path(object.question, object),
                    remote: true, method: :post, class: 'vote-plus')
      .votes-sum
        p
          = object.votes_sum

      .votes-link.vote-minus
        - if object.kind_of? Question
          = link_to '-', vote_minus_question_path(object), remote: true, method: :post, class: 'vote-minus'
        - if object.kind_of? Answer
          = link_to('-', vote_minus_question_answer_path(object.question, object),
                    remote: true, method: :post, class: 'vote-minus')

  - else
    .votes-sum
      p
        = object.votes_sum