config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers:
    {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations'
    }

  devise_scope :user do
    get 'email_required', to: 'registrations#email_required'
    post 'create_with_email', to: 'registrations#create_with_email'
    resources :users
  end

  root 'questions#index'
  get 'search', to: 'sphinx#search'

  concern :voteable do
    member do
      post 'vote_plus'
      post 'vote_minus'
      post 're_vote'
    end
  end

  concern :commentable do
    resources :comments, only: [:create, :show]
  end

  concern :tagged do
    get 'tagged/:tag', on: :collection, action: 'tagged_list', as: 'tagged'
  end

  resources :questions, concerns: [:voteable, :commentable, :tagged] do
    post 'subscribe', on: :member
    post 'unsubscribe', on: :member

    resources :answers, concerns: [:voteable, :commentable] do
      post 'best_answer', on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create]
      end
    end
  end

end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Sof
    = Gon::Base.render_data
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    .navbar.navbar-default.navbar-static-top
      .container
        .navbar-header
          button.navbar-toggle data-target="#navbar-ex-collapse" data-toggle="collapse" type="button"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
        #navbar-ex-collapse.collapse.navbar-collapse
          ul.nav.navbar-nav
            li
              = link_to 'Home', root_path
            li
              = link_to 'Questions', questions_path

          .search-form
            = form_for SearchQuery.new, url: '/search', method: :get, html: { class: 'form-inline' } do |f|
              .form-group
                label Search in:
                = f.collection_select :index, SearchQuery::INDICES, :itself, :pluralize, { include_blank: 'Everywhere' }, class: 'form-control search-location-select'
              .form-group
                = f.text_field :q, class: 'search-query form-control'
              .form-group
                = f.submit 'Search', class: 'btn'

    .section
      .container
        .row
          .col-md-6
            h1 StackOverflow clone
          .col-md-6
            .row
              .sign-info
                - if user_signed_in?
                  div
                    p= "Hi, #{current_user.email}"
                    p= "Your reputation is: #{current_user.reputation}"
                    p= link_to 'Profile', user_path(current_user)
                  = link_to 'Sign out', destroy_user_session_path, method: :delete
                - else
                  = link_to 'Sign in', new_user_session_path
                  span or
                  = link_to 'Sign up', new_user_registration_path
            .row
              .actions-menu
              - if can?(:create, Question)
                = link_to 'Ask question', new_question_path, class: 'btn btn-info'

    .section
      .container
        .row.flash-msgs
          - if notice
            .alert.alert-success role='alert'
              = notice
          - if alert
            .alert.alert-warning role='alert'
              = alert

    .container
      .row
        = yield

    footer.footer
      .container
        p
          | Stackoverflow clone. 2016